// console.log(Math.PI);
// console.log(Math.sqrt(9));
// console.log(Math.round(2.49));
// console.log(Math.ceil(2.3));
// console.log(Math.ceil(-2.3));
// console.log(Math.floor(2.3));
// console.log(Math.sign(31));
// console.log(Math.pow(2, 3));
// console.log(Math.abs(-44.5));
// console.log(Math.min(23, 34, 56, 67));
// const random = Math.random();
// console.log(random);
// const randombetween0_10 = Math.random() * 10;
// console.log(randombetween0_10);
